var posts =
[
    {
        "nome": "Questão LGBT na RPD da Coreia",
        "link": "https://www.facebook.com/OOutroLadodaCoreiadoNorte/photos/a.940537479353525/2983693268371259",
        "texto": "Não há direitos gays na Coreia do Norte ao mesmo tempo que não há perseguição. Os direitos são necessidades dos gays no ocidente pois eles são perseguidos. As pessoas passaram a se identificar como gays quando houve a necessidade de se unir contra uma opressão comum que sofriam - a relação sexual entre pessoas do mesmo gênero. <br> A Coreia Popular talvez seja uma das nações menos machistas do mundo, de modo que não há perseguição com a 'feminilidade' que designam aqui no ocidente como algo de gays e mulheres. Um relato de um desertor diz que ele viajou de metrô sentado no colo de um amigo certa vez, esse tipo de situação aqui no ocidente já seria motivo para discriminação e até violência, mas na Coreia do Norte, foi tratado como algo normal, talvez até um gesto de companheirismo. <br> Não há pessoas que se reconheçam como sendo “gays” na Coreia Popular, o que há são pessoas do mesmo gênero que, no seu íntimo, praticam sexo. Por que não se desenvolveu dentro da própria Coreia o indivíduo que se afirme 'gay' já que esse processo, com o tempo, surgiu em vários países do ocidente? Bem, a construção de algo novo se dá ao confronto acirrado de ideias opostas, das contradições, e acirramento da luta de classes que integra dentro de si manifestações chauvinistas para a exploração de um grupo sobre outro. Como a Coreia Popular nunca combateu a relação homoafetiva, nunca incentivou uma cultura de estereotipação e discriminação das pessoas sob conceitos machistas ocidentais e orientais, não se criou as bases conflitantes para surgir pessoas que se reconheçam como gays . São todos cidadãos norte coreanos e sua intimidade é um detalhe que não interfere em nada em seus direitos no país ou em outros aspectos da vida cotidiana. <br> Dessa forma, as duas informações que temos sobre a Coreia Popular são verdadeiras: Não há qualquer perseguição à prática homossexual e ao mesmo tempo que não há direitos gays já que não se faz necessário. <br><br><br> Declaração do Partido do Trabalho da Coreia acerca da questão homossexual:<br>«Nós, como um país socialista, abraçamos a ciência e o racionalismo e reconhecemos que muitas pessoas nascem com a homossexualidade como um traço genético, algo que pode ser inato ou desenvolvido ao longo de sua vida, e defendemos que essas pessoas sejam tratadas com o devido respeito. Os homossexuais, na RPDC, nunca foram, de maneira alguma, ser sujeitos à repressão e à perseguição, tal como acontece em muitos países capitalistas. No entanto, como comunistas, colocamos grande ênfase na moralidade e na harmonia social. Desta forma, rejeitamos a cultura gay ocidental, que promove o consumismo, o classismo, a banalização das relações humanas, o hedonismo e a promiscuidade.»"
    },
    {
        "nome": "Direitos da mulher na RPD da Coreia",
        "link": "https://facebook.com/",
        "texto": "blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla blablabla "
    },
    {
        "nome": "Eleições na RPD da Coreia",
        "link": "https://facebook.com/",
        "texto": "outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro<br>post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post outro post "
    }
]